### ISSUE TITLE
issue when running the create_database.py

### ISSUE THREAD

**Issue by ZhihongMiao** [pixegami/langchain-rag-tutorial#3]
I am really new in this area. I just download your code and try to run it in the anaconda environment using PyCharm. But I met below error. I have installed all the packages mentioned in the requirements.txt. Could you please comment what happened here? Thanks.

Traceback (most recent call last):
  File "C:\Users\PycharmProjects\rag_tutorial\create_database.py", line 1, in <module>
    from langchain.document_loaders import DirectoryLoader
  File "C:\Users\AppData\Local\anaconda3\envs\pytorch\lib\site-packages\langchain\__init__.py", line 8, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "C:\Users\AppData\Local\anaconda3\envs\pytorch\lib\site-packages\langchain\agents\__init__.py", line 2, in <module>
    from langchain.agents.agent import Agent
  File "C:\Users\AppData\Local\anaconda3\envs\pytorch\lib\site-packages\langchain\agents\agent.py", line 2
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

Process finished with exit code 1

**Comment by pedrocferreira** [comment]
This seems to be a Python version error, if you are using lower than 3.7, update the environment to 3.8
` __future__`  was included in 3.7
